name: Libreta personal.
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
# SITE CONFIGURATION
baseurl: ""
url: "https://leolerena.github.io"
